# Generated by Django 5.2.9 on 2026-01-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
